server:
  port: 8086
spring:
  application:
    name: api-gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost


zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    order-service:
      path: /orders/**
      serviceId: order-service
      stripPrefix: true
    product-service:
      path: /products/**
      serviceId: product-service
      stripPrefix: true
    customer-service:
      path: /customers/**
      serviceId: customer-service
      stripPrefix: true
    cart-command-service:
      path: /cart_command/**
      serviceId: cart-command-service
      stripPrefix: true
    cart-query-service:
      path: /cart_query/**
      serviceId: cart-query-service
      stripPrefix: true
